### ISSUE TITLE
[BUG] The randomizer crashes when I'm trying to load the EU version of XD

### ISSUE THREAD

**Issue by Pyjamaa** [rotobash/pokemon-ngc-rando#5]
**Describe the bug**
The randomizer crashes when I'm trying to load the EU version of XD

**Expected behavior**
No crash.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 8.1

**Additional context**
Errortext:
System.Exception: Unknown region!
   at XDCommon.Utility.ISOExtractor.ExtractISO() in H:\Projects\Pokemon-XD-Tool-Sharp\Pokemon-XD-Common\Utility\Files\ISOExtractor.cs:line 64
   at Randomizer.MainForm.loadIsoButton_Click(Object sender, EventArgs e) in H:\Projects\Pokemon-XD-Tool-Sharp\Pokemon-XD-Tool\MainForm.cs:line 52
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by rotobash** [comment]
Thanks for the report!

I have fixed this (see #4) although I haven't made a new release for it, my bad, but I can do that now. I wanted to include colosseum randomization in there but I got a bit side-tracked with work.

Please download the latest release when you can.
